import type { Metadata } from "next";
import { Nunito, Montserrat, Bebas_Neue } from "next/font/google";
import { Header } from "@/components/navigation/header";
import { ScrollArea } from "@/components/ui/scroll-area";
import "./globals.css";
import DotGrid from "@/components/backgrounds/dot-grid";


const nunito = Nunito({
    variable: "--font-nunit",
    display: 'swap',
    subsets: ["latin"],
});

const montserrat = Montserrat({
    variable: "--font-monts",
    display: 'swap',
    subsets: ["latin"],
});

const bebas = Bebas_Neue({
    variable: "--font-bebas",
    display: 'swap',
    weight: '400',
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Jesus Ramirez",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`
                    ${nunito.variable} 
                    ${montserrat.variable} 
                    ${bebas.variable} 
                    antialiased dark
                    relative
                    overflow-hidden
                    h-screen max-w-screen
                `}
            >

                <ScrollArea className="h-screen max-w-screen relative">
                    <div className="absolute w-full h-full">
                        <DotGrid
                            dotSize={5}
                            gap={15}
                            baseColor="#271E37"
                            activeColor="#5227FF"
                            proximity={120}
                            shockRadius={250}
                            shockStrength={5}
                            resistance={750}
                            returnDuration={1.5}
                        />
                    </div>
                    <main className="min-h-screen relative" >
                        {children}
                    </main>
                </ScrollArea>
            </body>
        </html>
    );
}
