import type { Metadata } from "next";
import { Nunito, Montserrat, Bebas_Neue } from "next/font/google";
import { Header } from "@/components/navigation/header";
import { ScrollArea } from "@/components/ui/scroll-area";
import "./globals.css";


const nunito = Nunito({
    variable: "--font-nunit",
    display: 'swap',
    subsets: ["latin"],
});

const montserrat = Montserrat({
    variable: "--font-monts",
    display: 'swap',
    subsets: ["latin"],
});

const bebas = Bebas_Neue({
    variable: "--font-bebas",
    display: 'swap',
    weight: '400',
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Jesus Ramirez",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`
                    ${nunito.variable} 
                    ${montserrat.variable} 
                    ${bebas.variable} 
                    antialiased dark
                    overflow-hidden
                `}
            >
                <ScrollArea className="h-screen max-w-screen">
                    {/* <Header /> */}
                    <main className="min-h-screen">
                        {children}
                    </main>
                </ScrollArea>
            </body>
        </html>
    );
}
